In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import math
import platform

df = pd.read_csv(r'C:\Users\컴퓨터\Documents\[부캠][basic] 심화프로젝트\2025_Airbnb_NYC_listings.csv') #----- 자기 경로 설정!!

In [3]:
df_host = df[['host_id','host_name','host_since','host_location','host_response_time','host_response_rate','host_acceptance_rate','host_is_superhost','host_listings_count','host_identity_verified']]
df_host

,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_identity_verified
0,62165,Michael,2009-12-11,"New York, NY",NaN,NaN,NaN,f,1.0,t
1,157798,Irene,2010-07-04,"New York, NY",NaN,NaN,100%,f,1.0,t
2,165789,Sarah,2010-07-13,"New York, NY",within a few hours,100%,40%,f,1.0,t
3,166532,Matthew,2010-07-14,"New York, NY",within an hour,100%,97%,t,1.0,t
4,168525,Gustavo,2010-07-16,"New York, NY",within an hour,100%,100%,t,2.0,t
...,...,...,...,...,...,...,...,...,...,...
22303,40019013,Cecilia,2015-07-30,"New York, NY",NaN,NaN,NaN,f,1.0,t
22304,483056418,Kristina,2022-10-10,"New York, NY",within an hour,100%,80%,t,24.0,t
22305,30283594,Global Luxury Suites,2015-03-30,"Hawthorne, NJ",within an hour,94%,99%,f,619.0,t
22306,407304997,Boomerang,2021-06-15,"New York, NY",within an hour,89%,100%,f,26.0,t
22307,483056418,Kristina,2022-10-10,"New York, NY",within an hour,100%,80%,t,24.0,t

In [4]:
df_lct = df[['neighbourhood','neighbourhood_group_cleansed','latitude','longitude']]
df_lct

,neighbourhood,neighbourhood_group_cleansed,latitude,longitude
0,Neighborhood highlights,Brooklyn,40.673760,-73.966110
1,Neighborhood highlights,Manhattan,40.792454,-73.940742
2,Neighborhood highlights,Brooklyn,40.684420,-73.980680
3,Neighborhood highlights,Manhattan,40.818058,-73.946671
4,Neighborhood highlights,Brooklyn,40.710651,-73.950874
...,...,...,...,...
22303,NaN,Manhattan,40.813794,-73.952399
22304,NaN,Brooklyn,40.685500,-73.919510
22305,NaN,Manhattan,40.745290,-73.979380
22306,NaN,Manhattan,40.757133,-73.983124
22307,NaN,Brooklyn,40.685500,-73.919510

In [5]:
df_info = df[['property_type','room_type','accommodates','bedrooms','beds','bathrooms','amenities']]
df_info

,property_type,room_type,accommodates,bedrooms,beds,bathrooms,amenities
0,Private room in rental unit,Private room,1,1.0,1.0,1.0,"[""Refrigerator"", ""Dishes and silverware"", ""Wif..."
1,Private room in condo,Private room,2,1.0,1.0,1.0,"[""Oven"", ""Blender"", ""Luggage dropoff allowed"",..."
2,Private room in home,Private room,2,5.0,5.0,2.5,"[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir..."
3,Entire home,Entire home/apt,2,1.0,1.0,1.0,"[""Fire extinguisher"", ""Clothing storage: close..."
4,Private room in rental unit,Private room,2,1.0,1.0,1.0,"[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L..."
...,...,...,...,...,...,...,...
22303,Private room in rental unit,Private room,1,1.0,1.0,1.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ..."
22304,Private room in rental unit,Private room,2,1.0,0.0,1.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ..."
22305,Entire rental unit,Entire home/apt,5,2.0,3.0,2.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ..."
22306,Entire rental unit,Entire home/apt,4,2.0,2.0,1.0,"[""Oven"", ""Gym"", ""Blender"", ""Dedicated workspac..."
22307,Private room in rental unit,Private room,2,1.0,0.0,1.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ..."

In [6]:
df_price = df[['price','minimum_nights','maximum_nights','availability_365','instant_bookable']]
df_price

,price,minimum_nights,maximum_nights,availability_365,instant_bookable
0,$200.00,90,365,362,f
1,$82.00,30,999,204,f
2,$765.00,3,60,326,f
3,$139.00,2,45,25,f
4,$130.00,4,45,38,f
...,...,...,...,...,...
22303,$72.00,30,365,358,f
22304,$58.00,30,365,363,f
22305,$299.00,30,365,99,f
22306,$200.00,30,365,365,t
22307,$58.00,30,365,363,f

In [7]:
df_review = df[['number_of_reviews','reviews_per_month','review_scores_rating','review_scores_cleanliness','review_scores_communication','first_review','last_review']]
df_review

,number_of_reviews,reviews_per_month,review_scores_rating,review_scores_cleanliness,review_scores_communication,first_review,last_review
0,9,0.05,4.88,4.80,5.00,2010-12-11,2013-05-10
1,102,0.58,4.77,4.76,4.90,2010-10-04,2023-12-09
2,43,0.28,4.70,4.52,4.88,2012-07-09,2023-08-30
3,241,1.36,4.85,4.50,4.96,2010-08-28,2025-02-21
4,274,1.54,4.82,4.61,4.88,2010-08-02,2025-01-03
...,...,...,...,...,...,...,...
22303,0,NaN,NaN,NaN,NaN,NaN,NaN
22304,0,NaN,NaN,NaN,NaN,NaN,NaN
22305,0,NaN,NaN,NaN,NaN,NaN,NaN
22306,0,NaN,NaN,NaN,NaN,NaN,NaN
22307,0,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_notion = df[['host_id','host_name','host_since','host_location','host_response_time','host_response_rate','host_acceptance_rate','host_is_superhost','host_listings_count','host_identity_verified',
                'neighbourhood','neighbourhood_group_cleansed','latitude','longitude',
                'property_type','room_type','accommodates','bedrooms','beds','bathrooms','amenities',
                'price','minimum_nights','maximum_nights','availability_365','instant_bookable',
                'number_of_reviews','reviews_per_month','review_scores_rating','review_scores_cleanliness','review_scores_communication','first_review','last_review']]
df_notion

,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_identity_verified,...,maximum_nights,availability_365,instant_bookable,number_of_reviews,reviews_per_month,review_scores_rating,review_scores_cleanliness,review_scores_communication,first_review,last_review
0,62165,Michael,2009-12-11,"New York, NY",NaN,NaN,NaN,f,1.0,t,...,365,362,f,9,0.05,4.88,4.80,5.00,2010-12-11,2013-05-10
1,157798,Irene,2010-07-04,"New York, NY",NaN,NaN,100%,f,1.0,t,...,999,204,f,102,0.58,4.77,4.76,4.90,2010-10-04,2023-12-09
2,165789,Sarah,2010-07-13,"New York, NY",within a few hours,100%,40%,f,1.0,t,...,60,326,f,43,0.28,4.70,4.52,4.88,2012-07-09,2023-08-30
3,166532,Matthew,2010-07-14,"New York, NY",within an hour,100%,97%,t,1.0,t,...,45,25,f,241,1.36,4.85,4.50,4.96,2010-08-28,2025-02-21
4,168525,Gustavo,2010-07-16,"New York, NY",within an hour,100%,100%,t,2.0,t,...,45,38,f,274,1.54,4.82,4.61,4.88,2010-08-02,2025-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22303,40019013,Cecilia,2015-07-30,"New York, NY",NaN,NaN,NaN,f,1.0,t,...,365,358,f,0,NaN,NaN,NaN,NaN,NaN,NaN
22304,483056418,Kristina,2022-10-10,"New York, NY",within an hour,100%,80%,t,24.0,t,...,365,363,f,0,NaN,NaN,NaN,NaN,NaN,NaN
22305,30283594,Global Luxury Suites,2015-03-30,"Hawthorne, NJ",within an hour,94%,99%,f,619.0,t,...,365,99,f,0,NaN,NaN,NaN,NaN,NaN,NaN
22306,407304997,Boomerang,2021-06-15,"New York, NY",within an hour,89%,100%,f,26.0,t,...,365,365,t,0,NaN,NaN,NaN,NaN,NaN,NaN
22307,483056418,Kristina,2022-10-10,"New York, NY",within an hour,100%,80%,t,24.0,t,...,365,363,f,0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# df_host = df[['host_id','host_name','host_since','host_location','host_response_time','host_response_rate','host_acceptance_rate','host_is_superhost','host_listings_count','host_identity_verified']]
# df_lct = df[['neighbourhood','neighbourhood_group_cleansed','latitude','longitude']]
# df_info = df[['property_type','room_type','accommodates','bedrooms','beds','bathrooms','amenities']]
# df_price = df[['price','minimum_nights','maximum_nights','availability_365','instant_bookable']]
# df_review = df[['number_of_reviews','reviews_per_month','review_scores_rating','review_scores_cleanliness','review_scores_communication','first_review','last_review']]

# df_notion = df[['host_id','host_name','host_since','host_location','host_response_time','host_response_rate','host_acceptance_rate','host_is_superhost','host_listings_count','host_identity_verified',
#                 'neighbourhood','neighbourhood_group_cleansed','latitude','longitude',
#                 'property_type','room_type','accommodates','bedrooms','beds','bathrooms','amenities',
#                 'price','minimum_nights','maximum_nights','availability_365','instant_bookable',
#                 'number_of_reviews','reviews_per_month','review_scores_rating','review_scores_cleanliness','review_scores_communication','first_review','last_review']]

In [10]:
df_notion.head()

,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_identity_verified,...,maximum_nights,availability_365,instant_bookable,number_of_reviews,reviews_per_month,review_scores_rating,review_scores_cleanliness,review_scores_communication,first_review,last_review
0,62165,Michael,2009-12-11,"New York, NY",NaN,NaN,NaN,f,1.0,t,...,365,362,f,9,0.05,4.88,4.80,5.00,2010-12-11,2013-05-10
1,157798,Irene,2010-07-04,"New York, NY",NaN,NaN,100%,f,1.0,t,...,999,204,f,102,0.58,4.77,4.76,4.90,2010-10-04,2023-12-09
2,165789,Sarah,2010-07-13,"New York, NY",within a few hours,100%,40%,f,1.0,t,...,60,326,f,43,0.28,4.70,4.52,4.88,2012-07-09,2023-08-30
3,166532,Matthew,2010-07-14,"New York, NY",within an hour,100%,97%,t,1.0,t,...,45,25,f,241,1.36,4.85,4.50,4.96,2010-08-28,2025-02-21
4,168525,Gustavo,2010-07-16,"New York, NY",within an hour,100%,100%,t,2.0,t,...,45,38,f,274,1.54,4.82,4.61,4.88,2010-08-02,2025-01-03

In [11]:
df_notion.head(7).T

,0,1,2,3,4,5,6
host_id,62165,157798,165789,166532,168525,169927,15991
host_name,Michael,Irene,Sarah,Matthew,Gustavo,Hubert,Allen & Irina
host_since,2009-12-11,2010-07-04,2010-07-13,2010-07-14,2010-07-16,2010-07-17,2009-05-06
host_location,"New York, NY","New York, NY","New York, NY","New York, NY","New York, NY","Saint-Aubin-sur-Scie, France","New York, NY"
host_response_time,NaN,NaN,within a few hours,within an hour,within an hour,NaN,within an hour
host_response_rate,NaN,NaN,100%,100%,100%,NaN,100%
host_acceptance_rate,NaN,100%,40%,97%,100%,NaN,100%
host_is_superhost,f,f,f,t,t,f,t
host_listings_count,1.0,1.0,1.0,1.0,2.0,2.0,1.0
host_identity_verified,t,t,t,t,t,t,t
neighbourhood,Neighborhood highlights,Neighborhood highlights,Neighborhood highlights,Neighborhood highlights,Neighborhood highlights,NaN,NaN
neighbourhood_group_cleansed,Brooklyn,Manhattan,Brooklyn,Manhattan,Brooklyn,Manhattan,Brooklyn
latitude,40.67376,40.792454,40.68442,40.818058,40.710651,40.76203,40.70935
longitude,-73.96611,-73.940742,-73.98068,-73.946671,-73.950874,-73.98869,-73.95342
property_type,Private room in rental unit,Private room in condo,Private room in home,Entire home,Private room in rental unit,Private room in rental unit,Entire rental unit
room_type,Private room,Private room,Private room,Entire home/apt,Private room,Private room,Entire home/apt
accommodates,1,2,2,2,2,2,3
bedrooms,1.0,1.0,5.0,1.0,1.0,1.0,2.0
beds,1.0,1.0,5.0,1.0,1.0,1.0,1.0
bathrooms,1.0,1.0,2.5,1.0,1.0,NaN,1.0
amenities,"[""Refrigerator"", ""Dishes and silverware"", ""Wif...","[""Oven"", ""Blender"", ""Luggage dropoff allowed"",...","[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir...","[""Fire extinguisher"", ""Clothing storage: close...","[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L...","[""Kitchen"", ""Air conditioning"", ""Dishes and si...","[""Oven"", ""Fire extinguisher"", ""Extra pillows a..."
price,$200.00,$82.00,$765.00,$139.00,$130.00,$139.00,$96.00
minimum_nights,90,30,3,2,4,30,30
maximum_nights,365,999,60,45,45,1125,120
availability_365,362,204,326,25,38,365,173
instant_bookable,f,f,f,f,f,f,f
number_of_reviews,9,102,43,241,274,44,194
reviews_per_month,0.05,0.58,0.28,1.36,1.54,0.25,1.01
review_scores_rating,4.88,4.77,4.7,4.85,4.82,4.86,4.58
review_scores_cleanliness,4.8,4.76,4.52,4.5,4.61,4.83,4.85
review_scores_communication,5.0,4.9,4.88,4.96,4.88,5.0,4.8
first_review,2010-12-11,2010-10-04,2012-07-09,2010-08-28,2010-08-02,2010-08-31,2009-05-25
last_review,2013-05-10,2023-12-09,2023-08-30,2025-02-21,2025-01-03,2019-01-03,2024-10-05

In [12]:
df['neighbourhood'].value_counts(dropna=False)

neighbourhood
Neighborhood highlights    12262
NaN                        10046
Name: count, dtype: int64

In [13]:
%pip install folium

Requirement already satisfied: folium in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from folium) (2.4.1)
Requirement already satisfied: requests in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from folium) (2.32.5)
Requirement already satisfied: xyzservices in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from folium) (2025.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests->folium) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests->folium) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\컴퓨터\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests->folium) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import pandas as pd
import folium
from folium.plugins import FastMarkerCluster

# (이전에 df = pd.read_csv('listings.csv') 코드로 데이터를 불러왔다고 가정할게!)

Long = -73.80
Lat = 40.80

# 위도와 경도 데이터를 리스트 형태로 묶어주기
locations = list(zip(df.latitude, df.longitude))

# 중심 좌표(location)와 초기 확대 비율(zoom_start)을 설정하여 기본 지도 생성
map1 = folium.Map(location=[Lat, Long], zoom_start=9)

# 대량의 마커를 빠르게 렌더링하고 클러스터링(그룹화)해 주는 FastMarkerCluster 추가
FastMarkerCluster(data=locations).add_to(map1)

# 지도 출력
map1

In [18]:
from folium.plugins import HeatMap


m=folium.Map([40.7128,-74.0060],zoom_start=11)

HeatMap(df[['latitude','longitude']].dropna(),radius=8,gradient={0.2:'blue',0.4:'purple',0.6:'orange',1.0:'red'}).add_to(m)

display(m)